### ISSUE TITLE
Multiple aab files

### ISSUE THREAD

**Issue by vahidlazio** [ch4vi/bitrise-step-bundle-universal-apk#1]
A support for having multiple aabs files and producing multiple named apks is needed.

**Comment by vahidlazio** [comment]
This can be achieved with having both name of apk and name of aab configurable in the bitrise step configuration.

**Comment by ch4vi** [comment]
I can't see the benefits of that. You can concatenate the step in bitrise with the different aab files.

**Comment by vahidlazio** [comment]
Yes, but all of them name `universal.apk` which has a problem with overriding, I already fixed this problem with naming the app name so the apk and `apps.apks` are named so there is no problem of overriding and same names. 

You can find the respective branch here. 
https://github.com/vahidlazio/bitrise-step-bundle-universal-apk/tree/origin/feature/app_name_apk

**Comment by ch4vi** [comment]
It was added in v0.0.5.
Sorry about the delay.
