### ISSUE TITLE
Automatically copy generated apk into $BITRISE_DEPLOY_DIR

### ISSUE THREAD

**Issue by tir38** [ch4vi/bitrise-step-bundle-universal-apk#2]
Other gradle apk-generating steps do this. It would be nice if it was included in this step too.

https://github.com/bitrise-steplib/steps-gradle-runner/blob/8def79b61e3185d8af1316a6a5ae603c9e227bd1/step.yml#L5

https://github.com/bitrise-steplib/steps-gradle-runner/blob/8def79b61e3185d8af1316a6a5ae603c9e227bd1/main.go#L397

**Comment by ch4vi** [comment]
I see what you mean. Currently I'm a little busy but I will check it, it does not seem difficult.
Thank you for your feedback.

**Comment by ch4vi** [comment]
It will be included in the coming version c0574e8 
if you need it sooner, It can be archived with the **Deploy to Bitrise.io** step.

**Comment by ch4vi** [comment]
https://github.com/bitrise-io/bitrise-steplib/pull/2213#event-2782626020
